# bundle exec jekyll serve --host=0.0.0.0

title: MycilaNTP
description: A simple and efficient NTP library for ESP32 / Arduino
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
